spring:
  application:
    name: @project.artifactId@
  app:
    name: ${spring.application.name}
server:
  port: 8080
management:
  server:
    port: 18080
  endpoints:
    web:
      exposure:
        include: "*"

# Spring Log
logging:
  level:
    root: INFO

# Swagger Custom Configs
spring-doc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    enabled: true
  api-docs:
    path: /football-league-manager/v3/api-docs
    enabled: true