spring:
  application:
    name: @project.artifactId@
  app:
    name: ${spring.application.name}
server:
  port: 8080
management:
  server:
    port: 18080
  endpoints:
    web:
      exposure:
        include: "*"

# Spring Log
logging:
  level:
    root: INFO