spring:
  application:
    name: @project.artifactId@
  app:
    name: ${spring.application.name}
  datasource:
    url: jdbc:postgresql:///football-league-manager
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    table: flyway_schema_history_football_league_manager
server:
  port: 8080
management:
  server:
    port: 18080
  endpoints:
    web:
      exposure:
        include: "*"

# Spring Log
logging:
  level:
    root: INFO

# Swagger Custom Configs
spring-doc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    enabled: true
  api-docs:
    path: /football-league-manager/v3/api-docs
    enabled: true